server_connect_timeout: 5000
listeners:
  - query_port: 25577
    motd: '&cServer not found'
    tab_list: SERVER
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.md-5.net: pvp
    ping_passthrough: true
    priorities:
      - fake
    bind_local_address: true
    host: 0.0.0.0:25565
    max_players: 0
    tab_size: 60
    force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
    - bungeecord.command.alert
    - bungeecord.command.end
    - bungeecord.command.ip
    - bungeecord.command.reload
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.send
    - bungeecord.command.find
    - bungeecord.command.end
    - mainserverplugin.admin.connect
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  HYONSU:
    - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 07509ee2-a00c-4003-89a4-9d5bfb948c08
online_mode: true
forge_support: false
disabled_commands:
  - bungee
  - perms
servers:
  fake:
    motd: ''
    address: localhost:0
    restricted: false
